# Generated by Django 6.0.3 on 2026-04-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disease",
            old_name="common_symptoms",
            new_name="symptoms",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="risk_level",
        ),
        migrations.AddField(
            model_name="disease",
            name="category",
            field=models.CharField(default="General", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disease",
            name="contagious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disease",
            name="precautions",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disease",
            name="risk_factors",
            field=models.JSONField(blank=True, default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disease",
            name="severity",
            field=models.CharField(default=[], max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="disease",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="report",
            name="disease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.disease"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
