# Generated by Django 6.0.3 on 2026-04-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_familymember"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="diet",
            field=models.TextField(blank=True, null=True),
        ),
    ]
